import ProjectDescription

let workspace = Workspace(
    name: "Assignment",
    projects: [
        // Dependency
        [
            .relativeToRoot("Modules/Dependency/Dependency")
        ],
        // Core
        [
            .relativeToRoot("Modules/Core/Network"),

            .relativeToRoot("Modules/Core/CoreContainer")
        ],
        // Feature
        [
            .relativeToRoot("Modules/Feature/GitHubProfile"),
            .relativeToRoot("Modules/Feature/GitHubSearch"),
            .relativeToRoot("Modules/Feature/MainTab"),

            .relativeToRoot("Modules/Feature/FeatureContainer")
        ],
        // App
        [
            .relativeToRoot("Modules/App")
        ]
    ].flatMap { $0 },
    generationOptions: .options(
        enableAutomaticXcodeSchemes: true,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: false
    )
)
